USE trabajofinalintegrador;

INSERT INTO features (id, name, icon) 
VALUES (1, 'Cocina', 'faSink'),
(2, 'Aire acondicionado', 'faSnowflake'),
(3, 'Estacionamiento Gratuito', 'faCar'),
(4, 'Wifi', 'faWifi'),
(5, 'Televisor', 'faTv'),
(6, 'Apto mascotas', 'faPaw'),
(7, 'Pileta', 'faSwimmer');

/*Modifico los valores con los datos nuevos de features para el consumo de la API (usar los de arriba)*/

INSERT INTO features (id, name, icon) 
VALUES (1, 'kitchen_1', 'FaSink'),
(2, 'kitchen_2', 'MdOutlineKitchen'),
(3, 'snow_flake_1', 'FaSnowflake'),
(4, 'snow_flake_2', 'BsSnow2'),
(5, 'car_1', 'FaCar'),
(6, 'car_2', 'IoCarSport'),
(7, 'wifi_1', 'FaWifi'),
(8, 'wifi_2', 'RiHomeWifiFill'),
(9, 'tv_1', 'FaTv'),
(10, 'tv_2', 'GiTv'),
(11, 'tv_3', 'GiTvRemote'),
(12, 'tv_4', 'IoTv'),
(13, 'tv_5', 'IoIosTv'),
(14, 'pet_friendly_1', 'MdOutlinePets'),
(15, 'pet_friendly_2', 'FaDog'),
(16, 'swimming_pool_1', 'FaSwimmer'),
(17, 'swimming_pool_2', 'FaSwimmingPool'),
(18, 'arrow_1', 'MdArrowBackIos'),
(19, 'arrow_2', 'IoIosArrowDroprightCircle'),
(20, 'user_1', 'FaUserAlt'),
(21, 'user_2', 'ImUser'),
(22, 'calendar_1', 'IoMdCalendar'),
(23, 'calendar_2', 'IoCalendarSharp'),
(24, 'search_1', 'ImSearch'),
(25, 'search_2', 'BiSearchAlt'),
(26, 'location_1', 'MdLocationOn'), 
(27, 'location_2', 'MdOutlineLocationOn'), 
(28, 'eye_1', 'AiOutlineEyeInvisible'), 
(29, 'eye_2', 'AiOutlineEye'), 
(30, 'eye_3', 'RiEyeCloseFill'),
(31, 'eye_4', 'ImEye'),
(32, 'heart_1', 'RiHeartLine'),
(33, 'heart_2', 'BsSuitHeartFill'),
(34, 'share_1', 'IoShareSocialOutline'),
(35, 'share_2', 'MdOutlineScreenShare'),
(36, 'clock_1', 'AiOutlineClockCircle'),
(37, 'clock_2', 'GiCuckooClock'),
(38, 'tornado_1', 'GiTornado'),
(39, 'credit_card_1', 'BsFillCreditCardFill'),
(40, 'credit_card_2', 'FaRegCreditCard'),
(41, 'smoking_free_1', 'MdSmokeFree'),
(42, 'smoking_free_2', 'IoLogoNoSmoking'),
(43, 'smoking_allowed_1', 'MdSmokingRooms'),
(44, 'smoking_allowed_2', 'GiSmokingPipe'),
(45, 'not_accesible_1', 'MdNotAccessible'),
(46, 'no_wifi_1', 'MdSignalWifiConnectedNoInternet3'),
(47, 'party_1', 'GiPartyPopper'),
(48, 'star_1', 'MdStarRate'),
(49, 'star_2', 'MdOutlineStarHalf'),
(50, 'star_3', 'GiStarFormation'),
(51, 'plus_1', 'FiPlusSquare'), 
(52, 'plus_2', 'FaPlus'), 
(53, 'minus_1', 'FiMinusSquare'), 
(54, 'minus_2', 'FaMinus'), 
(55, 'facebook_1', 'TiSocialFacebookCircular'), 
(56, 'facebook_2', 'TiSocialFacebook'), 
(57, 'twitter_1', 'TiSocialTwitter'), 
(58, 'twitter_2', 'TiSocialTwitterCircular'), 
(59, 'linkedin_1', 'TiSocialLinkedin'), 
(60, 'linkedin_2', 'TiSocialLinkedinCircular'),
(61, 'instagram_1', 'TiSocialInstagram'),
(62, 'youtube_1', 'TiSocialYoutube'),
(63, 'github_1', 'TiSocialGithub'),
(64, 'email_1', 'TiSocialAtCircular'),
(65, 'hamburguer_1', 'FiMenu'),
(66, 'hamburguer_2', 'CgMenuGridO'),
(67, 'exit_1', 'ImExit'),
(68, 'exit_2', 'BiExit');

SELECT *
FROM features;